### ISSUE TITLE
FASTFLOOR macro in srdnoise23.c has wrong ')' in EOL

### ISSUE THREAD

**Issue by fnaith** [stegu/perlin-noise#1]
In srdnoise23.c Line: 49, there is a macro :

`#define FASTFLOOR(x) ( ((int)(x)<=(x))) ? ((int)x) : (((int)x)-1) )`

but it should be `#define FASTFLOOR(x) ( ((int)(x)<=(x))) ? ((int)x) : (((int)x)-1)`, I guess?

Maybe it is just that this repository not sync with website yet.

**Comment by stegu** [comment]
Better yet, add an extra left-parenthesis at the beginning. Macro expansion
should not be allowed to swallow the top level parenthesis, for full safety
against hard-to-find bugs due to operator priority errors.

Sorry about the error. Will fix as soon as I have access to a proper
keyboard again.

**Comment by fnaith** [comment]
These noise functions are used by literally everywhere : P

But people always use them without sdnoise1234 and srdnoise23.

May a tiny compiler error causes this situation.

I wonder how many library will update after fixing those typo and post on the website. lol

**Comment by stegu** [comment]
Fixed. Thanks for pointing out the error!
