### ISSUE TITLE
Way to set seed?

### ISSUE THREAD

**Issue by 8-BIT-DEV** [stegu/perlin-noise#5]
Is there A way to set the seed

**Comment by stegu** [comment]
A sort-of equivalent of setting a seed for Perlin noise (and similar
functions) is to add a random spatial offset to the coordinates, e.g
using noise(x,y) and noise(x+43.7, y-17.1) to get two different
patterns. Another way is to use separate slices of 3D noise to get
different 2D noise fields: noise(x, y, 0) and noise(x, y, 7) look
different.

If you want a traditional seed for the pseudo-random gradients, it is
a small thing to edit the code to add a "seed" integer to the first
integer sent to the permutation polynomial for scrambling, but beware
that changing the seed in this manner will create a pattern that is
not completely uncorrelated to the pattern with another seed. The zero
crossings for the function will be at the exact same positions
regardless of that seed, so you might still want to use a coordinate
offset to make the two patterns dissimilar enough.

Perlin noise in its traditional implementations does not allow for a
seed to be set, but some use cases might of course still benefit from
it. Please feel free to add it yourself if you need it. I am reluctant
to create yet another version to maintain.
